### PR TITLE
Fixed functional stuff

### LINKED ISSUE #3: Remove() breaks expiration
Hi, this looks really promising, but has some unexpected behaviour:

```
    cache = ttlcache.NewCache()
    cache.SetExpirationCallback(func(key string, value interface{}) {
        fmt.Printf("This key(%s) has expired\n", key)
    })

    cache.SetWithTTL("keyWithTTL", "value", time.Duration(2 * time.Second))
    cache.Set("key", "value")
    //result = cache.Remove("key")

    value, exists = cache.Get("keyWithTTL")
    if exists {
        fmt.Printf("got %s for keyWithTTL\n", value)
    }
    count = cache.Count()
    fmt.Printf("cache has %d keys\n", count)

    <-time.After(3 * time.Second)

    value, exists = cache.Get("keyWithTTL")
    if exists {
        fmt.Printf("got %s for keyWithTTL\n", value)
    } else {
        fmt.Println("keyWithTTL has gone")
    }
    count = cache.Count()
    fmt.Printf("cache has %d keys\n", count)
```

The above prints:

> got value for keyWithTTL
> cache has 2 keys
> This key(keyWithTTL) has expired
> keyWithTTL has gone
> cache has 1 keys

as expected. But if you uncomment the Remove() call, you get:

> got value for keyWithTTL
> cache has 1 keys
> keyWithTTL has gone
> cache has 1 keys

so it's in some weird inconsistent state, where you can't get the key, but Count() suggests it's there, and the ExpirationCallback never fired.

### LINKED ISSUE #4: Remove() causes panic: runtime error: index out of range
This:

```
cache = ttlcache.NewCache()
cache.Set("key", "value")
//cache.Remove("key")
count = cache.Count()
fmt.Printf("cache has %d keys\n", count)
```

prints this:

> cache has 1 keys

But if you uncomment the Remove() call, you get this:

> panic: runtime error: index out of range
> goroutine 1 [running]:
> panic(0x76ed00, 0xc820014120)
>     /software/vertres/installs/go/src/runtime/panic.go:464 +0x3e6
> github.com/diegobernardes/ttlcache.priorityQueue.Swap(0x0, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff)
>     /nfs/users/nfs_s/sb10/src/go/src/github.com/diegobernardes/ttlcache/priority_queue.go:54 +0x1f9
> github.com/diegobernardes/ttlcache.(_priorityQueue).Swap(0xc8200d8020, 0x0, 0xffffffffffffffff)
>     <autogenerated>:3 +0xaa
> container/heap.Remove(0x7f595f9ac750, 0xc8200d8020, 0x0, 0x0, 0x0)
>     /software/vertres/installs/go/src/container/heap/heap.go:74 +0x6c
> github.com/diegobernardes/ttlcache.(_priorityQueue).remove(0xc8200d8020, 0xc8200e0000)
>     /nfs/users/nfs_s/sb10/src/go/src/github.com/diegobernardes/ttlcache/priority_queue.go:35 +0x56
> github.com/diegobernardes/ttlcache.(*Cache).Remove(0xc8200de000, 0x7daeb8, 0x3, 0x6dd860)
>     /nfs/users/nfs_s/sb10/src/go/src/github.com/diegobernardes/ttlcache/cache.go:167 +0xed
> [...]

### PR DESCRIPTION
**Pull request by ReneKroon**
I fixed the outstanding issues and everything else i could find.

Performance in the benchmarks is about half, but at least it's correct. I might try to see what i can get back there later on.

fixes #3 
fixes #4

### CODE REVIEW

**Comment by diegobernardes** [comment]
@ReneKroon do you want to maintain this project? I could transfer it, i'm really out of time to do the maintenance it need.

**Comment by ReneKroon** [comment]
hi, i can take ownership if you don't have the time. For the next year or
2-3 im using this lib in an application so i have an interest :-)

**Comment by diegobernardes** [comment]
Gonna be better for everyone one. Thanks for the support :+1:

**Comment by diegobernardes** [comment]
Please, delete your ttlcache repository so i can do the transfer.

**Comment by ReneKroon** [comment]
removed it..

**Pull request merged**
